swagger: '2.0'

info:
  title: Example API
  version: "0.1"

consumes:
  - application/json

produces:
  - application/json

paths:
  /match:
      get:
        operationId: rock_paper_scissors.rest_api.match
        parameters:
         - name: player
           in: query
           required: true
           type: string
           enum:
             - Rock
             - Scissors
             - Paper
        responses:
          200:
            description: Returns a json with the match details

